In [3]:
S={4,3,-6}
print(S)
S.add(-10)
print(S)
S.pop()
print(S)

{-6, 3, 4}
{-6, 3, 4, -10}
{3, 4, -10}


In [23]:
x=int(input('Enter a number: '))
year=(x//365)
print(year)
month=(x%365)//30
print(month)
days=(x%365)%30
print(days)
print('year:',year,'month(s):',month,'day(s):',days)

Enter a number: 400
1
1
5
year: 1 month(s): 1 day(s): 5


In [66]:
rows,colmns=(4,4)
matrix=[[0]*colmns]*rows

last=3
print(matrix)
for i in range(4):  
    matrix[i][0]=1
    matrix[i][last]=1
    for j in range(4):
        matrix[0][j]=1
        matrix[last][j]=1
    
print(matrix)


[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]
[[1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1]]


In [86]:
import numpy as np
rows=int(input('Enter rows:'))
coloumns=int(input('Enter coloumns:'))
matrix=np.ones((rows,coloumns))
#matrix=np.zeros((rows,coloumns))
#for i in range(rows):  
    #matrix[i][0]=1
    #matrix[i][coloumns-1]=1
    #for j in range(coloumns):
        #matrix[0][j]=1
       #matrix[rows-1][j]=1
matrix[1:rows-1,1:coloumns-1]=0
print(matrix)

Enter rows:3
Enter coloumns:4
[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]
