In [1]:
import numpy as np

array=np.zeros(10)
array[3]=1
print (array)

[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


In [11]:
                 #start,stop,step
matrix=np.arange(0.01,1.01,0.01).reshape(10,10) #reshape used in making into a matrix
print(matrix)

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


In [19]:
matrix=np.ones((8,8))
matrix[::2, 1::2] = 0
matrix[1::2, ::2] = 0
print (matrix)
#x[::2, 1::2] = 1: This line uses array slicing to select every other row (starting from the first row) and every other column (starting from the second column) in the array 'x' and sets their elements to ones. The slice ::2 means "every second element" in both the rows and columns, while the slice 1::2 means "every second element, starting from the second element".

#x[1::2, ::2] = 1: This line uses array slicing to select every other row (starting from the second row) and every other column (starting from the first column) in the array 'x' and sets their elements to ones. The slice 1::2 means "every second element, starting from the second element" in both the rows and columns.

#or we can use

np.tile(np.array([[1,0],[0,1]]),(4,4)) #first row,second row repeated 4 times 


[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [22]:
! pip install requests

Defaulting to user installation because normal site-packages is not writeable


In [23]:
! pip install beautifulsoup4

Defaulting to user installation because normal site-packages is not writeable


In [10]:
import requests
from bs4 import BeautifulSoup
import csv
! pip install lxml 

Defaulting to user installation because normal site-packages is not writeable


In [4]:
with open ("C:\\Artificial Intelligence Course/test.txt") as file: 
    y = file.readlines()
print(y)
print(len(y))

# y = [i.strip() for i in y ]   #is a list comprehension
# y
for i in y:
    print(i.strip())


['This is a test file, and this is Saturday\n', 'this is another test \n', 'this is ItSharks']
3
This is a test file, and this is Saturday
this is another test
this is ItSharks


In [11]:
with open ('C:\\Artificial Intelligence Course/simple.html') as html_file:
        soup = BeautifulSoup(html_file, 'lxml') # parser, #parsing  --> to convert byte code into simple code

In [12]:
soup

<!DOCTYPE html>
<html class="no-js" lang="">
<head>
<title> Web Scrapping session  </title>
<meta charset="utf-8"/>
<link href="css/normalize.css" rel="stylesheet"/>
<link href="css/main.css" rel="stylesheet"/>
<style>
		h1 {
			color: red;
			font-size: 50px;
		}

		#site_title2 {
			color: black;
			font-size: 20px;
		}


		.article {
			background-color: #60d6a5;
		}




	</style>
</head>
<body>
<h1 id="site_title">    This is a web scrapping session before el eid    </h1>
<h2> Another h2 Website </h2>
<h3>Test Website with h3</h3>
<hr/>
<hr/>
<section>
<h2> This is a new section </h2>
		this is a new section for testing and debugging


	</section>

Test Anything


	<hr/>
<hr/>
<article>

		this is new article

	</article>
<hr/>
<img class="css-9pa8cd" src="image.png"/>
<div class="article">
<h2>
<a href="https://google.com"> Download now </a>
</h2>
<p> This is a paragraph to explain how html works with web scrapping </p>
</div>
<hr/>
<div class="article">
<h2>
<a href="article_2.ht

In [14]:
website = requests.get("https://9animetv.to/home").text # website link ( URL ) 
print(type(website)) # returns string ( website code) 
website
# retirieve website html code ( i.e. syntax)

<class 'str'>


'<!DOCTYPE html>\n<html lang="en">\n<head>\n    <title>9anime Homepage: Best free anime to watch in HD quality</title>\n<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>\n<meta name="robots" content="index,follow"/>\n<meta http-equiv="content-language" content="en"/>\n<meta name="description" content="Watch latest anime in HD Quality and download your favorite anime from our fast anime website"/>\n<meta name="keywords" content="9anime, 9 anime, 9animeto, latest anime, watch anime online, free anime, anime free, online anime, anime website"/>\n<meta property="og:type" content="website"/>\n<meta property="og:url" content="https://9animetv.to/home"/>\n<meta property="og:title" content="9anime Homepage: Best free anime to watch in HD quality"/>\n<meta property="og:image" content="https://9animetv.to/images/capture.png"/>\n<meta property="og:image:width" content="650">\n<meta property="og:image:height" content="350">\n<meta property="og:description" content="Watch latest 

In [15]:
soup = BeautifulSoup(website , 'lxml') # parsing ( understand txt string as html tags, id, class)

In [16]:
print(soup.prettify())

<!DOCTYPE html>
<html lang="en">
 <head>
  <title>
   9anime Homepage: Best free anime to watch in HD quality
  </title>
  <meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
  <meta content="index,follow" name="robots"/>
  <meta content="en" http-equiv="content-language"/>
  <meta content="Watch latest anime in HD Quality and download your favorite anime from our fast anime website" name="description"/>
  <meta content="9anime, 9 anime, 9animeto, latest anime, watch anime online, free anime, anime free, online anime, anime website" name="keywords"/>
  <meta content="website" property="og:type"/>
  <meta content="https://9animetv.to/home" property="og:url"/>
  <meta content="9anime Homepage: Best free anime to watch in HD quality" property="og:title"/>
  <meta content="https://9animetv.to/images/capture.png" property="og:image"/>
  <meta content="650" property="og:image:width"/>
  <meta content="350" property="og:image:height"/>
  <meta content="Watch latest anime in H

In [18]:
title=soup.title.text
print(title)

9anime Homepage: Best free anime to watch in HD quality


In [30]:
import pandas as pd
df=pd.read_csv("C://Artificial Intelligence Course/archive/tested.csv")
print(df)

     PassengerId  Survived  Pclass  \
0            892         0       3   
1            893         1       3   
2            894         0       2   
3            895         0       3   
4            896         1       3   
..           ...       ...     ...   
413         1305         0       3   
414         1306         1       1   
415         1307         0       3   
416         1308         0       3   
417         1309         0       3   

                                             Name     Sex   Age  SibSp  Parch  \
0                                Kelly, Mr. James    male  34.5      0      0   
1                Wilkes, Mrs. James (Ellen Needs)  female  47.0      1      0   
2                       Myles, Mr. Thomas Francis    male  62.0      0      0   
3                                Wirz, Mr. Albert    male  27.0      0      0   
4    Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1      1   
..                                            ...     ...

In [36]:
print(type(df['Age']))
df['Age']=df['Age'].mean
print(df['Age'])

<class 'pandas.core.series.Series'>
0      <bound method NDFrame._add_numeric_operations....
1      <bound method NDFrame._add_numeric_operations....
2      <bound method NDFrame._add_numeric_operations....
3      <bound method NDFrame._add_numeric_operations....
4      <bound method NDFrame._add_numeric_operations....
                             ...                        
413    <bound method NDFrame._add_numeric_operations....
414    <bound method NDFrame._add_numeric_operations....
415    <bound method NDFrame._add_numeric_operations....
416    <bound method NDFrame._add_numeric_operations....
417    <bound method NDFrame._add_numeric_operations....
Name: Age, Length: 418, dtype: object


In [35]:
#%matplotlib inline
#from matplotlib import pyplot as plt

#df['Age'].plot.hist(title='Ages', bins=19)
#plt.xlabel('')
#plt.ylabel('')
#plt.show()

TypeError: no numeric data to plot

In [40]:
df.Embarked

0      Q
1      S
2      Q
3      S
4      S
      ..
413    S
414    C
415    S
416    S
417    C
Name: Embarked, Length: 418, dtype: object

In [42]:
df['Fare'].max()

512.3292

In [65]:
df['Age']=df['Age'].astype('str')
print(df['Age'])

0      <bound method NDFrame._add_numeric_operations....
1      <bound method NDFrame._add_numeric_operations....
2      <bound method NDFrame._add_numeric_operations....
3      <bound method NDFrame._add_numeric_operations....
4      <bound method NDFrame._add_numeric_operations....
                             ...                        
413    <bound method NDFrame._add_numeric_operations....
414    <bound method NDFrame._add_numeric_operations....
415    <bound method NDFrame._add_numeric_operations....
416    <bound method NDFrame._add_numeric_operations....
417    <bound method NDFrame._add_numeric_operations....
Name: Age, Length: 418, dtype: object


In [46]:
df.index

RangeIndex(start=0, stop=418, step=1)

In [48]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [49]:
x=df.columns.to_list()
print(x)
print(type(x))

['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked']
<class 'list'>


In [50]:
for i in df.Fare:
    if(i>246):
        print(i)
        

262.375
263.0
262.375
262.375
263.0
262.375
247.5208
512.3292
262.375


In [52]:
df[df.Survived==1]

PassengerId  Survived  Pclass  \
1            893         1       3   
4            896         1       3   
6            898         1       3   
8            900         1       3   
12           904         1       1   
..           ...       ...     ...   
409         1301         1       3   
410         1302         1       3   
411         1303         1       1   
412         1304         1       3   
414         1306         1       1   

                                                Name     Sex  \
1                   Wilkes, Mrs. James (Ellen Needs)  female   
4       Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   
6                               Connolly, Miss. Kate  female   
8          Abrahim, Mrs. Joseph (Sophie Halaut Easu)  female   
12     Snyder, Mrs. John Pillsbury (Nelle Stevenson)  female   
..                                               ...     ...   
409                        Peacock, Miss. Treasteall  female   
410                           Naughton, Miss. Hannah  female   
411  Minahan, Mrs. William Edward (Lillian E Thorpe)  female   
412                   Henriksson, Miss. Jenny Lovisa  female   
414                     Oliva y Ocana, Dona. Fermina  female   

                                                   Age  SibSp  Parch  \
1    <bound method NDFrame._add_numeric_operations....      1      0   
4    <bound method NDFrame._add_numeric_operations....      1      1   
6    <bound method NDFrame._add_numeric_operations....      0      0   
8    <bound method NDFrame._add_numeric_operations....      0      0   
12   <bound method NDFrame._add_numeric_operations....      1      0   
..                                                 ...    ...    ...   
409  <bound method NDFrame._add_numeric_operations....      1      1   
410  <bound method NDFrame._add_numeric_operations....      0      0   
411  <bound method NDFrame._add_numeric_operations....      1      0   
412  <bound method NDFrame._add_numeric_operations....      0      0   
414  <bound method NDFrame._add_numeric_operations....      0      0   

                 Ticket      Fare Cabin Embarked  
1                363272    7.0000   NaN        S  
4               3101298   12.2875   NaN        S  
6                330972    7.6292   NaN        Q  
8                  2657    7.2292   NaN        C  
12                21228   82.2667   B45        S  
..                  ...       ...   ...      ...  
409  SOTON/O.Q. 3101315   13.7750   NaN        S  
410              365237    7.7500   NaN        Q  
411               19928   90.0000   C78        Q  
412              347086    7.7750   NaN        S  
414            PC 17758  108.9000  C105        C  

[152 rows x 12 columns]

In [53]:
df['Embarked'][df.Survived==1]

1      S
4      S
6      Q
8      C
12     S
      ..
409    S
410    Q
411    Q
412    S
414    C
Name: Embarked, Length: 152, dtype: object

In [54]:
print(df.Age.dtype)

object


In [59]:
print(f"you have: {len(df.columns)} columns")

you have: 12 columns


In [60]:
df.describe

<bound method NDFrame.describe of      PassengerId  Survived  Pclass  \
0            892         0       3   
1            893         1       3   
2            894         0       2   
3            895         0       3   
4            896         1       3   
..           ...       ...     ...   
413         1305         0       3   
414         1306         1       1   
415         1307         0       3   
416         1308         0       3   
417         1309         0       3   

                                             Name     Sex  \
0                                Kelly, Mr. James    male   
1                Wilkes, Mrs. James (Ellen Needs)  female   
2                       Myles, Mr. Thomas Francis    male   
3                                Wirz, Mr. Albert    male   
4    Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   
..                                            ...     ...   
413                            Spector, Mr. Woolf    male   
414                  

In [62]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  418 non-null    int64  
 1   Survived     418 non-null    int64  
 2   Pclass       418 non-null    int64  
 3   Name         418 non-null    object 
 4   Sex          418 non-null    object 
 5   Age          418 non-null    object 
 6   SibSp        418 non-null    int64  
 7   Parch        418 non-null    int64  
 8   Ticket       418 non-null    object 
 9   Fare         417 non-null    float64
 10  Cabin        91 non-null     object 
 11  Embarked     418 non-null    object 
dtypes: float64(1), int64(5), object(6)
memory usage: 39.3+ KB


In [63]:
df.fillna('?')

PassengerId  Survived  Pclass  \
0            892         0       3   
1            893         1       3   
2            894         0       2   
3            895         0       3   
4            896         1       3   
..           ...       ...     ...   
413         1305         0       3   
414         1306         1       1   
415         1307         0       3   
416         1308         0       3   
417         1309         0       3   

                                             Name     Sex  \
0                                Kelly, Mr. James    male   
1                Wilkes, Mrs. James (Ellen Needs)  female   
2                       Myles, Mr. Thomas Francis    male   
3                                Wirz, Mr. Albert    male   
4    Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   
..                                            ...     ...   
413                            Spector, Mr. Woolf    male   
414                  Oliva y Ocana, Dona. Fermina  female   
415                  Saether, Mr. Simon Sivertsen    male   
416                           Ware, Mr. Frederick    male   
417                      Peter, Master. Michael J    male   

                                                   Age  SibSp  Parch  \
0    <bound method NDFrame._add_numeric_operations....      0      0   
1    <bound method NDFrame._add_numeric_operations....      1      0   
2    <bound method NDFrame._add_numeric_operations....      0      0   
3    <bound method NDFrame._add_numeric_operations....      0      0   
4    <bound method NDFrame._add_numeric_operations....      1      1   
..                                                 ...    ...    ...   
413  <bound method NDFrame._add_numeric_operations....      0      0   
414  <bound method NDFrame._add_numeric_operations....      0      0   
415  <bound method NDFrame._add_numeric_operations....      0      0   
416  <bound method NDFrame._add_numeric_operations....      0      0   
417  <bound method NDFrame._add_numeric_operations....      1      1   

                 Ticket     Fare Cabin Embarked  
0                330911   7.8292     ?        Q  
1                363272      7.0     ?        S  
2                240276   9.6875     ?        Q  
3                315154   8.6625     ?        S  
4               3101298  12.2875     ?        S  
..                  ...      ...   ...      ...  
413           A.5. 3236     8.05     ?        S  
414            PC 17758    108.9  C105        C  
415  SOTON/O.Q. 3101262     7.25     ?        S  
416              359309     8.05     ?        S  
417                2668  22.3583     ?        C  

[418 rows x 12 columns]